using Guna.UI2.WinForms;

using System.Drawing;
using System.Windows.Forms;

#nullable enable

namespace University_Timetable_and_Classroom_Management_System
{
    public partial class SchedulesForm
    {
        private void InitializeComponent()
        {
            DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
            pnlSidebar = new Guna.UI2.WinForms.Guna2Panel();
            lblSidebarFooter = new Guna.UI2.WinForms.Guna2HtmlLabel();
            btnNavigationSchedules = new Guna.UI2.WinForms.Guna2Button();
            btnNavigationFaculty = new Guna.UI2.WinForms.Guna2Button();
            btnNavigationTimeSlots = new Guna.UI2.WinForms.Guna2Button();
            btnNavigationClassrooms = new Guna.UI2.WinForms.Guna2Button();
            btnNavigationSubjects = new Guna.UI2.WinForms.Guna2Button();
            btnNavigationStudyYears = new Guna.UI2.WinForms.Guna2Button();
            btnNavigationBranches = new Guna.UI2.WinForms.Guna2Button();
            separatorSidebar = new Guna.UI2.WinForms.Guna2Separator();
            lblSidebarSubtitle = new Guna.UI2.WinForms.Guna2HtmlLabel();
            lblApplicationName = new Guna.UI2.WinForms.Guna2HtmlLabel();
            pnlMain = new Guna.UI2.WinForms.Guna2Panel();
            pnlWorkspace = new Guna.UI2.WinForms.Guna2Panel();
            pnlSchedulesTable = new Guna.UI2.WinForms.Guna2Panel();
            dgvSchedules = new Guna.UI2.WinForms.Guna2DataGridView();
            colScheduleId = new DataGridViewTextBoxColumn();
            colDayOfWeek = new DataGridViewTextBoxColumn();
            colSubject = new DataGridViewTextBoxColumn();
            colFacultyMember = new DataGridViewTextBoxColumn();
            colClassroom = new DataGridViewTextBoxColumn();
            colTimeSlot = new DataGridViewTextBoxColumn();
            colStudyYear = new DataGridViewTextBoxColumn();
            colBranch = new DataGridViewTextBoxColumn();
            colSection = new DataGridViewTextBoxColumn();
            lblTableSubtitle = new Guna.UI2.WinForms.Guna2HtmlLabel();
            lblTableTitle = new Guna.UI2.WinForms.Guna2HtmlLabel();
            pnlScheduleFilters = new Guna.UI2.WinForms.Guna2Panel();
            cmbStudyYearFilter = new Guna.UI2.WinForms.Guna2ComboBox();
            lblStudyYearFilter = new Guna.UI2.WinForms.Guna2HtmlLabel();
            cmbSectionFilter = new Guna.UI2.WinForms.Guna2ComboBox();
            lblSectionFilter = new Guna.UI2.WinForms.Guna2HtmlLabel();
            cmbFacultyFilter = new Guna.UI2.WinForms.Guna2ComboBox();
            lblFacultyFilter = new Guna.UI2.WinForms.Guna2HtmlLabel();
            pnlScheduleEditor = new Guna.UI2.WinForms.Guna2Panel();
            btnClearScheduleForm = new Guna.UI2.WinForms.Guna2Button();
            btnExportSchedulePdf = new Guna.UI2.WinForms.Guna2Button();
            btnGenerateSchedule = new Guna.UI2.WinForms.Guna2Button();
            btnDeleteSchedule = new Guna.UI2.WinForms.Guna2Button();
            btnUpdateSchedule = new Guna.UI2.WinForms.Guna2Button();
            btnAddSchedule = new Guna.UI2.WinForms.Guna2Button();
            cmbSection = new Guna.UI2.WinForms.Guna2ComboBox();
            lblSection = new Guna.UI2.WinForms.Guna2HtmlLabel();
            cmbBranch = new Guna.UI2.WinForms.Guna2ComboBox();
            lblBranch = new Guna.UI2.WinForms.Guna2HtmlLabel();
            cmbStudyYear = new Guna.UI2.WinForms.Guna2ComboBox();
            lblStudyYear = new Guna.UI2.WinForms.Guna2HtmlLabel();
            cmbTimeSlot = new Guna.UI2.WinForms.Guna2ComboBox();
            lblTimeSlot = new Guna.UI2.WinForms.Guna2HtmlLabel();
            cmbClassroom = new Guna.UI2.WinForms.Guna2ComboBox();
            lblClassroom = new Guna.UI2.WinForms.Guna2HtmlLabel();
            cmbFacultyMember = new Guna.UI2.WinForms.Guna2ComboBox();
            lblFacultyMember = new Guna.UI2.WinForms.Guna2HtmlLabel();
            cmbSubject = new Guna.UI2.WinForms.Guna2ComboBox();
            lblSubject = new Guna.UI2.WinForms.Guna2HtmlLabel();
            cmbDayOfWeek = new Guna.UI2.WinForms.Guna2ComboBox();
            lblDayOfWeek = new Guna.UI2.WinForms.Guna2HtmlLabel();
            txtScheduleId = new Guna.UI2.WinForms.Guna2TextBox();
            lblScheduleId = new Guna.UI2.WinForms.Guna2HtmlLabel();
            lblEditorSubtitle = new Guna.UI2.WinForms.Guna2HtmlLabel();
            lblEditorTitle = new Guna.UI2.WinForms.Guna2HtmlLabel();
            pnlSidebar.SuspendLayout();
            pnlMain.SuspendLayout();
            pnlWorkspace.SuspendLayout();
            pnlSchedulesTable.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvSchedules).BeginInit();
            pnlScheduleFilters.SuspendLayout();
            pnlScheduleEditor.SuspendLayout();
            SuspendLayout();
            pnlSidebar.BackColor = Color.Transparent;
            pnlSidebar.Controls.Add(lblSidebarFooter);
            pnlSidebar.Controls.Add(btnNavigationSchedules);
            pnlSidebar.Controls.Add(btnNavigationFaculty);
            pnlSidebar.Controls.Add(btnNavigationTimeSlots);
            pnlSidebar.Controls.Add(btnNavigationClassrooms);
            pnlSidebar.Controls.Add(btnNavigationSubjects);
            pnlSidebar.Controls.Add(btnNavigationStudyYears);
            pnlSidebar.Controls.Add(btnNavigationBranches);
            pnlSidebar.Controls.Add(separatorSidebar);
            pnlSidebar.Controls.Add(lblSidebarSubtitle);
            pnlSidebar.Controls.Add(lblApplicationName);
            pnlSidebar.Dock = DockStyle.Left;
            pnlSidebar.FillColor = Color.FromArgb(24, 38, 62);
            pnlSidebar.Location = new Point(0, 0);
            pnlSidebar.Name = "pnlSidebar";
            pnlSidebar.Size = new Size(240, 820);
            pnlSidebar.TabIndex = 0;
            lblSidebarFooter.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            lblSidebarFooter.BackColor = Color.Transparent;
            lblSidebarFooter.Font = new Font("Segoe UI", 9F);
            lblSidebarFooter.ForeColor = Color.FromArgb(148, 163, 184);
            lblSidebarFooter.Location = new Point(24, 771);
            lblSidebarFooter.Name = "lblSidebarFooter";
            lblSidebarFooter.Size = new Size(147, 17);
            lblSidebarFooter.TabIndex = 11;
            lblSidebarFooter.Text = "Academic Scheduling Suite";
            btnNavigationSchedules.BorderRadius = 8;
            btnNavigationSchedules.Checked = true;
            btnNavigationSchedules.Cursor = Cursors.Hand;
            btnNavigationSchedules.Enabled = false;
            btnNavigationSchedules.FillColor = Color.FromArgb(37, 99, 235);
            btnNavigationSchedules.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnNavigationSchedules.ForeColor = Color.White;
            btnNavigationSchedules.HoverState.FillColor = Color.FromArgb(29, 78, 216);
            btnNavigationSchedules.Location = new Point(24, 490);
            btnNavigationSchedules.Name = "btnNavigationSchedules";
            btnNavigationSchedules.Size = new Size(192, 44);
            btnNavigationSchedules.TabIndex = 10;
            btnNavigationSchedules.Text = "Schedules";
            btnNavigationSchedules.TextAlign = HorizontalAlignment.Left;
            btnNavigationSchedules.TextOffset = new Point(14, 0);
            btnNavigationFaculty.BorderRadius = 8;
            btnNavigationFaculty.Cursor = Cursors.Hand;
            btnNavigationFaculty.FillColor = Color.FromArgb(24, 38, 62);
            btnNavigationFaculty.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnNavigationFaculty.ForeColor = Color.FromArgb(226, 232, 240);
            btnNavigationFaculty.HoverState.FillColor = Color.FromArgb(36, 55, 86);
            btnNavigationFaculty.Location = new Point(24, 434);
            btnNavigationFaculty.Name = "btnNavigationFaculty";
            btnNavigationFaculty.Size = new Size(192, 44);
            btnNavigationFaculty.TabIndex = 9;
            btnNavigationFaculty.Text = "Faculty Members";
            btnNavigationFaculty.TextAlign = HorizontalAlignment.Left;
            btnNavigationFaculty.TextOffset = new Point(14, 0);
            btnNavigationTimeSlots.BorderRadius = 8;
            btnNavigationTimeSlots.Cursor = Cursors.Hand;
            btnNavigationTimeSlots.FillColor = Color.FromArgb(24, 38, 62);
            btnNavigationTimeSlots.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnNavigationTimeSlots.ForeColor = Color.FromArgb(226, 232, 240);
            btnNavigationTimeSlots.HoverState.FillColor = Color.FromArgb(36, 55, 86);
            btnNavigationTimeSlots.Location = new Point(24, 378);
            btnNavigationTimeSlots.Name = "btnNavigationTimeSlots";
            btnNavigationTimeSlots.Size = new Size(192, 44);
            btnNavigationTimeSlots.TabIndex = 8;
            btnNavigationTimeSlots.Text = "Time Slots";
            btnNavigationTimeSlots.TextAlign = HorizontalAlignment.Left;
            btnNavigationTimeSlots.TextOffset = new Point(14, 0);
            btnNavigationClassrooms.BorderRadius = 8;
            btnNavigationClassrooms.Cursor = Cursors.Hand;
            btnNavigationClassrooms.FillColor = Color.FromArgb(24, 38, 62);
            btnNavigationClassrooms.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnNavigationClassrooms.ForeColor = Color.FromArgb(226, 232, 240);
            btnNavigationClassrooms.HoverState.FillColor = Color.FromArgb(36, 55, 86);
            btnNavigationClassrooms.Location = new Point(24, 322);
            btnNavigationClassrooms.Name = "btnNavigationClassrooms";
            btnNavigationClassrooms.Size = new Size(192, 44);
            btnNavigationClassrooms.TabIndex = 7;
            btnNavigationClassrooms.Text = "Classrooms";
            btnNavigationClassrooms.TextAlign = HorizontalAlignment.Left;
            btnNavigationClassrooms.TextOffset = new Point(14, 0);
            btnNavigationSubjects.BorderRadius = 8;
            btnNavigationSubjects.Cursor = Cursors.Hand;
            btnNavigationSubjects.FillColor = Color.FromArgb(24, 38, 62);
            btnNavigationSubjects.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnNavigationSubjects.ForeColor = Color.FromArgb(226, 232, 240);
            btnNavigationSubjects.HoverState.FillColor = Color.FromArgb(36, 55, 86);
            btnNavigationSubjects.Location = new Point(24, 266);
            btnNavigationSubjects.Name = "btnNavigationSubjects";
            btnNavigationSubjects.Size = new Size(192, 44);
            btnNavigationSubjects.TabIndex = 6;
            btnNavigationSubjects.Text = "Subjects";
            btnNavigationSubjects.TextAlign = HorizontalAlignment.Left;
            btnNavigationSubjects.TextOffset = new Point(14, 0);
            btnNavigationStudyYears.BorderRadius = 8;
            btnNavigationStudyYears.Cursor = Cursors.Hand;
            btnNavigationStudyYears.FillColor = Color.FromArgb(24, 38, 62);
            btnNavigationStudyYears.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnNavigationStudyYears.ForeColor = Color.FromArgb(226, 232, 240);
            btnNavigationStudyYears.HoverState.FillColor = Color.FromArgb(36, 55, 86);
            btnNavigationStudyYears.Location = new Point(24, 210);
            btnNavigationStudyYears.Name = "btnNavigationStudyYears";
            btnNavigationStudyYears.Size = new Size(192, 44);
            btnNavigationStudyYears.TabIndex = 5;
            btnNavigationStudyYears.Text = "Study Years";
            btnNavigationStudyYears.TextAlign = HorizontalAlignment.Left;
            btnNavigationStudyYears.TextOffset = new Point(14, 0);
            btnNavigationBranches.BorderRadius = 8;
            btnNavigationBranches.Cursor = Cursors.Hand;
            btnNavigationBranches.FillColor = Color.FromArgb(24, 38, 62);
            btnNavigationBranches.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnNavigationBranches.ForeColor = Color.FromArgb(226, 232, 240);
            btnNavigationBranches.HoverState.FillColor = Color.FromArgb(36, 55, 86);
            btnNavigationBranches.Location = new Point(24, 154);
            btnNavigationBranches.Name = "btnNavigationBranches";
            btnNavigationBranches.Size = new Size(192, 44);
            btnNavigationBranches.TabIndex = 4;
            btnNavigationBranches.Text = "Branches";
            btnNavigationBranches.TextAlign = HorizontalAlignment.Left;
            btnNavigationBranches.TextOffset = new Point(14, 0);
            separatorSidebar.FillColor = Color.FromArgb(51, 65, 85);
            separatorSidebar.Location = new Point(24, 78);
            separatorSidebar.Name = "separatorSidebar";
            separatorSidebar.Size = new Size(192, 10);
            separatorSidebar.TabIndex = 2;
            lblSidebarSubtitle.BackColor = Color.Transparent;
            lblSidebarSubtitle.Font = new Font("Segoe UI", 9F);
            lblSidebarSubtitle.ForeColor = Color.FromArgb(148, 163, 184);
            lblSidebarSubtitle.Location = new Point(26, 52);
            lblSidebarSubtitle.Name = "lblSidebarSubtitle";
            lblSidebarSubtitle.Size = new Size(133, 17);
            lblSidebarSubtitle.TabIndex = 1;
            lblSidebarSubtitle.Text = "Classroom Management";
            lblApplicationName.BackColor = Color.Transparent;
            lblApplicationName.Font = new Font("Segoe UI Semibold", 17F, FontStyle.Bold);
            lblApplicationName.ForeColor = Color.White;
            lblApplicationName.Location = new Point(24, 20);
            lblApplicationName.Name = "lblApplicationName";
            lblApplicationName.Size = new Size(216, 33);
            lblApplicationName.TabIndex = 0;
            lblApplicationName.Text = "University Timetable";
            pnlMain.Controls.Add(pnlWorkspace);
            pnlMain.Dock = DockStyle.Fill;
            pnlMain.FillColor = Color.FromArgb(245, 247, 250);
            pnlMain.Location = new Point(240, 0);
            pnlMain.Name = "pnlMain";
            pnlMain.Size = new Size(1260, 820);
            pnlMain.TabIndex = 1;
            pnlWorkspace.Controls.Add(pnlSchedulesTable);
            pnlWorkspace.Controls.Add(pnlScheduleFilters);
            pnlWorkspace.Controls.Add(pnlScheduleEditor);
            pnlWorkspace.Dock = DockStyle.Fill;
            pnlWorkspace.FillColor = Color.FromArgb(245, 247, 250);
            pnlWorkspace.Location = new Point(0, 0);
            pnlWorkspace.Name = "pnlWorkspace";
            pnlWorkspace.Padding = new Padding(28, 24, 28, 28);
            pnlWorkspace.Size = new Size(1260, 820);
            pnlWorkspace.TabIndex = 1;
            pnlSchedulesTable.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            pnlSchedulesTable.BackColor = Color.Transparent;
            pnlSchedulesTable.BorderColor = Color.FromArgb(226, 232, 240);
            pnlSchedulesTable.BorderRadius = 8;
            pnlSchedulesTable.BorderThickness = 1;
            pnlSchedulesTable.Controls.Add(dgvSchedules);
            pnlSchedulesTable.Controls.Add(lblTableSubtitle);
            pnlSchedulesTable.Controls.Add(lblTableTitle);
            pnlSchedulesTable.FillColor = Color.White;
            pnlSchedulesTable.Location = new Point(28, 416);
            pnlSchedulesTable.Name = "pnlSchedulesTable";
            pnlSchedulesTable.Size = new Size(1204, 288);
            pnlSchedulesTable.TabIndex = 1;
            dgvSchedules.AllowUserToAddRows = false;
            dgvSchedules.AllowUserToDeleteRows = false;
            dgvSchedules.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = Color.FromArgb(248, 250, 252);
            dataGridViewCellStyle1.ForeColor = Color.FromArgb(30, 41, 59);
            dataGridViewCellStyle1.SelectionBackColor = Color.FromArgb(219, 234, 254);
            dataGridViewCellStyle1.SelectionForeColor = Color.FromArgb(30, 64, 175);
            dgvSchedules.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            dgvSchedules.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = Color.FromArgb(15, 23, 42);
            dataGridViewCellStyle2.Font = new Font("Segoe UI Semibold", 11F, FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = Color.White;
            dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(15, 23, 42);
            dataGridViewCellStyle2.SelectionForeColor = Color.White;
            dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
            dgvSchedules.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            dgvSchedules.ColumnHeadersHeight = 48;
            dgvSchedules.Columns.AddRange(new DataGridViewColumn[] { colScheduleId, colDayOfWeek, colSubject, colFacultyMember, colClassroom, colTimeSlot, colStudyYear, colBranch, colSection });
            dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = Color.White;
            dataGridViewCellStyle3.Font = new Font("Segoe UI", 11F);
            dataGridViewCellStyle3.ForeColor = Color.FromArgb(30, 41, 59);
            dataGridViewCellStyle3.SelectionBackColor = Color.FromArgb(219, 234, 254);
            dataGridViewCellStyle3.SelectionForeColor = Color.FromArgb(30, 64, 175);
            dataGridViewCellStyle3.WrapMode = DataGridViewTriState.False;
            dgvSchedules.DefaultCellStyle = dataGridViewCellStyle3;
            dgvSchedules.GridColor = Color.FromArgb(226, 232, 240);
            dgvSchedules.Location = new Point(24, 78);
            dgvSchedules.MultiSelect = false;
            dgvSchedules.Name = "dgvSchedules";
            dgvSchedules.ReadOnly = true;
            dgvSchedules.RowHeadersVisible = false;
            dgvSchedules.RowTemplate.Height = 46;
            dgvSchedules.Size = new Size(1156, 186);
            dgvSchedules.TabIndex = 2;
            dgvSchedules.ThemeStyle.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 250, 252);
            dgvSchedules.ThemeStyle.AlternatingRowsStyle.ForeColor = Color.FromArgb(30, 41, 59);
            dgvSchedules.ThemeStyle.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(219, 234, 254);
            dgvSchedules.ThemeStyle.AlternatingRowsStyle.SelectionForeColor = Color.FromArgb(30, 64, 175);
            dgvSchedules.ThemeStyle.GridColor = Color.FromArgb(226, 232, 240);
            dgvSchedules.ThemeStyle.HeaderStyle.BackColor = Color.FromArgb(15, 23, 42);
            dgvSchedules.ThemeStyle.HeaderStyle.Font = new Font("Segoe UI Semibold", 11F, FontStyle.Bold);
            dgvSchedules.ThemeStyle.HeaderStyle.HeaightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            dgvSchedules.ThemeStyle.HeaderStyle.Height = 48;
            dgvSchedules.ThemeStyle.ReadOnly = true;
            dgvSchedules.ThemeStyle.RowsStyle.Font = new Font("Segoe UI", 11F);
            dgvSchedules.ThemeStyle.RowsStyle.ForeColor = Color.FromArgb(30, 41, 59);
            dgvSchedules.ThemeStyle.RowsStyle.Height = 46;
            dgvSchedules.ThemeStyle.RowsStyle.SelectionBackColor = Color.FromArgb(219, 234, 254);
            dgvSchedules.ThemeStyle.RowsStyle.SelectionForeColor = Color.FromArgb(30, 64, 175);
            colScheduleId.DataPropertyName = "ScheduleID";
            colScheduleId.FillWeight = 38F;
            colScheduleId.HeaderText = "ID";
            colScheduleId.Name = "colScheduleId";
            colScheduleId.ReadOnly = true;
            colDayOfWeek.DataPropertyName = "DayOfWeek";
            colDayOfWeek.FillWeight = 65F;
            colDayOfWeek.HeaderText = "Day";
            colDayOfWeek.Name = "colDayOfWeek";
            colDayOfWeek.ReadOnly = true;
            colSubject.DataPropertyName = "SubjectID";
            colSubject.HeaderText = "Subject";
            colSubject.Name = "colSubject";
            colSubject.ReadOnly = true;
            colFacultyMember.DataPropertyName = "FacultyMemberID";
            colFacultyMember.HeaderText = "Faculty";
            colFacultyMember.Name = "colFacultyMember";
            colFacultyMember.ReadOnly = true;
            colClassroom.DataPropertyName = "ClassroomID";
            colClassroom.FillWeight = 68F;
            colClassroom.HeaderText = "Room";
            colClassroom.Name = "colClassroom";
            colClassroom.ReadOnly = true;
            colTimeSlot.DataPropertyName = "TimeSlotID";
            colTimeSlot.FillWeight = 75F;
            colTimeSlot.HeaderText = "Time";
            colTimeSlot.Name = "colTimeSlot";
            colTimeSlot.ReadOnly = true;
            colStudyYear.DataPropertyName = "StudyYearID";
            colStudyYear.FillWeight = 72F;
            colStudyYear.HeaderText = "Year";
            colStudyYear.Name = "colStudyYear";
            colStudyYear.ReadOnly = true;
            colBranch.DataPropertyName = "BranchID";
            colBranch.FillWeight = 72F;
            colBranch.HeaderText = "Branch";
            colBranch.Name = "colBranch";
            colBranch.ReadOnly = true;
            colSection.DataPropertyName = "SectionID";
            colSection.FillWeight = 72F;
            colSection.HeaderText = "Section";
            colSection.Name = "colSection";
            colSection.ReadOnly = true;
            lblTableSubtitle.BackColor = Color.Transparent;
            lblTableSubtitle.Font = new Font("Segoe UI", 9F);
            lblTableSubtitle.ForeColor = Color.FromArgb(100, 116, 139);
            lblTableSubtitle.Location = new Point(24, 43);
            lblTableSubtitle.Name = "lblTableSubtitle";
            lblTableSubtitle.Size = new Size(235, 17);
            lblTableSubtitle.TabIndex = 1;
            lblTableSubtitle.Text = "Review and select timetable session records.";
            lblTableTitle.BackColor = Color.Transparent;
            lblTableTitle.Font = new Font("Segoe UI Semibold", 13F, FontStyle.Bold);
            lblTableTitle.ForeColor = Color.FromArgb(15, 23, 42);
            lblTableTitle.Location = new Point(24, 18);
            lblTableTitle.Name = "lblTableTitle";
            lblTableTitle.Size = new Size(109, 25);
            lblTableTitle.TabIndex = 0;
            lblTableTitle.Text = "Timetable Records";
            pnlScheduleFilters.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            pnlScheduleFilters.BackColor = Color.Transparent;
            pnlScheduleFilters.BorderRadius = 10;
            pnlScheduleFilters.Controls.Add(cmbStudyYearFilter);
            pnlScheduleFilters.Controls.Add(lblStudyYearFilter);
            pnlScheduleFilters.Controls.Add(cmbSectionFilter);
            pnlScheduleFilters.Controls.Add(lblSectionFilter);
            pnlScheduleFilters.Controls.Add(cmbFacultyFilter);
            pnlScheduleFilters.Controls.Add(lblFacultyFilter);
            pnlScheduleFilters.FillColor = Color.White;
            pnlScheduleFilters.Location = new Point(28, 306);
            pnlScheduleFilters.Name = "pnlScheduleFilters";
            pnlScheduleFilters.Size = new Size(1204, 84);
            pnlScheduleFilters.TabIndex = 2;
            cmbStudyYearFilter.BackColor = Color.Transparent;
            cmbStudyYearFilter.BorderColor = Color.FromArgb(203, 213, 225);
            cmbStudyYearFilter.BorderRadius = 8;
            cmbStudyYearFilter.DrawMode = DrawMode.OwnerDrawFixed;
            cmbStudyYearFilter.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbStudyYearFilter.FocusedColor = Color.FromArgb(37, 99, 235);
            cmbStudyYearFilter.FocusedState.BorderColor = Color.FromArgb(37, 99, 235);
            cmbStudyYearFilter.Font = new Font("Segoe UI", 10F);
            cmbStudyYearFilter.ForeColor = Color.FromArgb(15, 23, 42);
            cmbStudyYearFilter.ItemHeight = 30;
            cmbStudyYearFilter.Location = new Point(456, 36);
            cmbStudyYearFilter.Name = "cmbStudyYearFilter";
            cmbStudyYearFilter.Size = new Size(180, 36);
            cmbStudyYearFilter.TabIndex = 5;
            lblStudyYearFilter.BackColor = Color.Transparent;
            lblStudyYearFilter.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
            lblStudyYearFilter.ForeColor = Color.FromArgb(15, 23, 42);
            lblStudyYearFilter.Location = new Point(456, 14);
            lblStudyYearFilter.Name = "lblStudyYearFilter";
            lblStudyYearFilter.Size = new Size(86, 17);
            lblStudyYearFilter.TabIndex = 4;
            lblStudyYearFilter.Text = "Year";
            cmbSectionFilter.BackColor = Color.Transparent;
            cmbSectionFilter.BorderColor = Color.FromArgb(203, 213, 225);
            cmbSectionFilter.BorderRadius = 8;
            cmbSectionFilter.DrawMode = DrawMode.OwnerDrawFixed;
            cmbSectionFilter.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbSectionFilter.FocusedColor = Color.FromArgb(37, 99, 235);
            cmbSectionFilter.FocusedState.BorderColor = Color.FromArgb(37, 99, 235);
            cmbSectionFilter.Font = new Font("Segoe UI", 10F);
            cmbSectionFilter.ForeColor = Color.FromArgb(15, 23, 42);
            cmbSectionFilter.ItemHeight = 30;
            cmbSectionFilter.Location = new Point(208, 36);
            cmbSectionFilter.Name = "cmbSectionFilter";
            cmbSectionFilter.Size = new Size(220, 36);
            cmbSectionFilter.TabIndex = 3;
            lblSectionFilter.BackColor = Color.Transparent;
            lblSectionFilter.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
            lblSectionFilter.ForeColor = Color.FromArgb(15, 23, 42);
            lblSectionFilter.Location = new Point(208, 14);
            lblSectionFilter.Name = "lblSectionFilter";
            lblSectionFilter.Size = new Size(70, 17);
            lblSectionFilter.TabIndex = 2;
            lblSectionFilter.Text = "Section";
            cmbFacultyFilter.BackColor = Color.Transparent;
            cmbFacultyFilter.BorderColor = Color.FromArgb(203, 213, 225);
            cmbFacultyFilter.BorderRadius = 8;
            cmbFacultyFilter.DrawMode = DrawMode.OwnerDrawFixed;
            cmbFacultyFilter.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbFacultyFilter.FocusedColor = Color.FromArgb(37, 99, 235);
            cmbFacultyFilter.FocusedState.BorderColor = Color.FromArgb(37, 99, 235);
            cmbFacultyFilter.Font = new Font("Segoe UI", 10F);
            cmbFacultyFilter.ForeColor = Color.FromArgb(15, 23, 42);
            cmbFacultyFilter.ItemHeight = 30;
            cmbFacultyFilter.Location = new Point(24, 36);
            cmbFacultyFilter.Name = "cmbFacultyFilter";
            cmbFacultyFilter.Size = new Size(156, 36);
            cmbFacultyFilter.TabIndex = 1;
            lblFacultyFilter.BackColor = Color.Transparent;
            lblFacultyFilter.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
            lblFacultyFilter.ForeColor = Color.FromArgb(15, 23, 42);
            lblFacultyFilter.Location = new Point(24, 14);
            lblFacultyFilter.Name = "lblFacultyFilter";
            lblFacultyFilter.Size = new Size(68, 17);
            lblFacultyFilter.TabIndex = 0;
            lblFacultyFilter.Text = "Faculty";
            pnlScheduleEditor.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            pnlScheduleEditor.BackColor = Color.Transparent;
            pnlScheduleEditor.BorderColor = Color.FromArgb(226, 232, 240);
            pnlScheduleEditor.BorderRadius = 8;
            pnlScheduleEditor.BorderThickness = 1;
            pnlScheduleEditor.Controls.Add(btnClearScheduleForm);
            pnlScheduleEditor.Controls.Add(btnExportSchedulePdf);
            pnlScheduleEditor.Controls.Add(btnGenerateSchedule);
            pnlScheduleEditor.Controls.Add(btnDeleteSchedule);
            pnlScheduleEditor.Controls.Add(btnUpdateSchedule);
            pnlScheduleEditor.Controls.Add(btnAddSchedule);
            pnlScheduleEditor.Controls.Add(cmbSection);
            pnlScheduleEditor.Controls.Add(lblSection);
            pnlScheduleEditor.Controls.Add(cmbBranch);
            pnlScheduleEditor.Controls.Add(lblBranch);
            pnlScheduleEditor.Controls.Add(cmbStudyYear);
            pnlScheduleEditor.Controls.Add(lblStudyYear);
            pnlScheduleEditor.Controls.Add(cmbTimeSlot);
            pnlScheduleEditor.Controls.Add(lblTimeSlot);
            pnlScheduleEditor.Controls.Add(cmbClassroom);
            pnlScheduleEditor.Controls.Add(lblClassroom);
            pnlScheduleEditor.Controls.Add(cmbFacultyMember);
            pnlScheduleEditor.Controls.Add(lblFacultyMember);
            pnlScheduleEditor.Controls.Add(cmbSubject);
            pnlScheduleEditor.Controls.Add(lblSubject);
            pnlScheduleEditor.Controls.Add(cmbDayOfWeek);
            pnlScheduleEditor.Controls.Add(lblDayOfWeek);
            pnlScheduleEditor.Controls.Add(txtScheduleId);
            pnlScheduleEditor.Controls.Add(lblScheduleId);
            pnlScheduleEditor.Controls.Add(lblEditorSubtitle);
            pnlScheduleEditor.Controls.Add(lblEditorTitle);
            pnlScheduleEditor.FillColor = Color.White;
            pnlScheduleEditor.Location = new Point(28, 24);
            pnlScheduleEditor.Name = "pnlScheduleEditor";
            pnlScheduleEditor.Size = new Size(1204, 260);
            pnlScheduleEditor.TabIndex = 0;
            btnClearScheduleForm.BorderColor = Color.FromArgb(203, 213, 225);
            btnClearScheduleForm.BorderRadius = 8;
            btnClearScheduleForm.BorderThickness = 1;
            btnClearScheduleForm.Cursor = Cursors.Hand;
            btnClearScheduleForm.FillColor = Color.FromArgb(100, 116, 139);
            btnClearScheduleForm.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            btnClearScheduleForm.ForeColor = Color.White;
            btnClearScheduleForm.HoverState.FillColor = Color.FromArgb(248, 250, 252);
            btnClearScheduleForm.Location = new Point(512, 204);
            btnClearScheduleForm.Name = "btnClearScheduleForm";
            btnClearScheduleForm.Size = new Size(108, 38);
            btnClearScheduleForm.TabIndex = 23;
            btnClearScheduleForm.Text = "Clear Form";
            btnExportSchedulePdf.BorderRadius = 8;
            btnExportSchedulePdf.Cursor = Cursors.Hand;
            btnExportSchedulePdf.FillColor = Color.FromArgb(16, 185, 129);
            btnExportSchedulePdf.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            btnExportSchedulePdf.ForeColor = Color.White;
            btnExportSchedulePdf.HoverState.FillColor = Color.FromArgb(5, 150, 105);
            btnExportSchedulePdf.Location = new Point(640, 204);
            btnExportSchedulePdf.Name = "btnExportSchedulePdf";
            btnExportSchedulePdf.Size = new Size(130, 38);
            btnExportSchedulePdf.TabIndex = 25;
            btnExportSchedulePdf.Text = "Export PDF";
            btnGenerateSchedule.BorderRadius = 8;
            btnGenerateSchedule.Cursor = Cursors.Hand;
            btnGenerateSchedule.FillColor = Color.FromArgb(15, 23, 42);
            btnGenerateSchedule.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            btnGenerateSchedule.ForeColor = Color.White;
            btnGenerateSchedule.HoverState.FillColor = Color.FromArgb(30, 41, 59);
            btnGenerateSchedule.Location = new Point(24, 204);
            btnGenerateSchedule.Name = "btnGenerateSchedule";
            btnGenerateSchedule.Size = new Size(130, 38);
            btnGenerateSchedule.TabIndex = 24;
            btnGenerateSchedule.Text = "Generate Timetable";
            btnDeleteSchedule.BorderRadius = 8;
            btnDeleteSchedule.Cursor = Cursors.Hand;
            btnDeleteSchedule.FillColor = Color.FromArgb(220, 38, 38);
            btnDeleteSchedule.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            btnDeleteSchedule.ForeColor = Color.White;
            btnDeleteSchedule.HoverState.FillColor = Color.FromArgb(185, 28, 28);
            btnDeleteSchedule.Location = new Point(392, 204);
            btnDeleteSchedule.Name = "btnDeleteSchedule";
            btnDeleteSchedule.Size = new Size(108, 38);
            btnDeleteSchedule.TabIndex = 22;
            btnDeleteSchedule.Text = "Delete";
            btnUpdateSchedule.BorderRadius = 8;
            btnUpdateSchedule.Cursor = Cursors.Hand;
            btnUpdateSchedule.FillColor = Color.FromArgb(37, 99, 235);
            btnUpdateSchedule.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            btnUpdateSchedule.ForeColor = Color.White;
            btnUpdateSchedule.HoverState.FillColor = Color.FromArgb(21, 94, 117);
            btnUpdateSchedule.Location = new Point(272, 204);
            btnUpdateSchedule.Name = "btnUpdateSchedule";
            btnUpdateSchedule.Size = new Size(108, 38);
            btnUpdateSchedule.TabIndex = 21;
            btnUpdateSchedule.Text = "Update";
            btnAddSchedule.BorderRadius = 8;
            btnAddSchedule.Cursor = Cursors.Hand;
            btnAddSchedule.FillColor = Color.FromArgb(22, 163, 74);
            btnAddSchedule.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            btnAddSchedule.ForeColor = Color.White;
            btnAddSchedule.HoverState.FillColor = Color.FromArgb(21, 128, 61);
            btnAddSchedule.Location = new Point(160, 204);
            btnAddSchedule.Name = "btnAddSchedule";
            btnAddSchedule.Size = new Size(108, 38);
            btnAddSchedule.TabIndex = 20;
            btnAddSchedule.Text = "Add";
            cmbSection.BackColor = Color.Transparent;
            cmbSection.BorderColor = Color.FromArgb(203, 213, 225);
            cmbSection.BorderRadius = 8;
            cmbSection.DrawMode = DrawMode.OwnerDrawFixed;
            cmbSection.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbSection.FocusedColor = Color.FromArgb(37, 99, 235);
            cmbSection.FocusedState.BorderColor = Color.FromArgb(37, 99, 235);
            cmbSection.Font = new Font("Segoe UI", 10F);
            cmbSection.ForeColor = Color.FromArgb(15, 23, 42);
            cmbSection.HoverState.BorderColor = Color.FromArgb(59, 130, 246);
            cmbSection.ItemHeight = 36;
            cmbSection.Location = new Point(24, 144);
            cmbSection.Name = "cmbSection";
            cmbSection.Size = new Size(160, 42);
            cmbSection.TabIndex = 19;
            lblSection.BackColor = Color.Transparent;
            lblSection.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            lblSection.ForeColor = Color.FromArgb(51, 65, 85);
            lblSection.Location = new Point(24, 119);
            lblSection.Name = "lblSection";
            lblSection.Size = new Size(47, 19);
            lblSection.TabIndex = 18;
            lblSection.Text = "Section";
            cmbBranch.BackColor = Color.Transparent;
            cmbBranch.BorderColor = Color.FromArgb(203, 213, 225);
            cmbBranch.BorderRadius = 8;
            cmbBranch.DrawMode = DrawMode.OwnerDrawFixed;
            cmbBranch.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbBranch.FocusedColor = Color.FromArgb(37, 99, 235);
            cmbBranch.FocusedState.BorderColor = Color.FromArgb(37, 99, 235);
            cmbBranch.Font = new Font("Segoe UI", 10F);
            cmbBranch.ForeColor = Color.FromArgb(15, 23, 42);
            cmbBranch.HoverState.BorderColor = Color.FromArgb(59, 130, 246);
            cmbBranch.ItemHeight = 36;
            cmbBranch.Location = new Point(1080, 74);
            cmbBranch.Name = "cmbBranch";
            cmbBranch.Size = new Size(100, 42);
            cmbBranch.TabIndex = 17;
            lblBranch.BackColor = Color.Transparent;
            lblBranch.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            lblBranch.ForeColor = Color.FromArgb(51, 65, 85);
            lblBranch.Location = new Point(1080, 49);
            lblBranch.Name = "lblBranch";
            lblBranch.Size = new Size(45, 19);
            lblBranch.TabIndex = 16;
            lblBranch.Text = "Branch";
            cmbStudyYear.BackColor = Color.Transparent;
            cmbStudyYear.BorderColor = Color.FromArgb(203, 213, 225);
            cmbStudyYear.BorderRadius = 8;
            cmbStudyYear.DrawMode = DrawMode.OwnerDrawFixed;
            cmbStudyYear.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbStudyYear.FocusedColor = Color.FromArgb(37, 99, 235);
            cmbStudyYear.FocusedState.BorderColor = Color.FromArgb(37, 99, 235);
            cmbStudyYear.Font = new Font("Segoe UI", 10F);
            cmbStudyYear.ForeColor = Color.FromArgb(15, 23, 42);
            cmbStudyYear.HoverState.BorderColor = Color.FromArgb(59, 130, 246);
            cmbStudyYear.ItemHeight = 36;
            cmbStudyYear.Location = new Point(904, 74);
            cmbStudyYear.Name = "cmbStudyYear";
            cmbStudyYear.Size = new Size(160, 42);
            cmbStudyYear.TabIndex = 15;
            lblStudyYear.BackColor = Color.Transparent;
            lblStudyYear.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            lblStudyYear.ForeColor = Color.FromArgb(51, 65, 85);
            lblStudyYear.Location = new Point(904, 49);
            lblStudyYear.Name = "lblStudyYear";
            lblStudyYear.Size = new Size(69, 19);
            lblStudyYear.TabIndex = 14;
            lblStudyYear.Text = "Year";
            cmbTimeSlot.BackColor = Color.Transparent;
            cmbTimeSlot.BorderColor = Color.FromArgb(203, 213, 225);
            cmbTimeSlot.BorderRadius = 8;
            cmbTimeSlot.DrawMode = DrawMode.OwnerDrawFixed;
            cmbTimeSlot.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbTimeSlot.FocusedColor = Color.FromArgb(37, 99, 235);
            cmbTimeSlot.FocusedState.BorderColor = Color.FromArgb(37, 99, 235);
            cmbTimeSlot.Font = new Font("Segoe UI", 10F);
            cmbTimeSlot.ForeColor = Color.FromArgb(15, 23, 42);
            cmbTimeSlot.HoverState.BorderColor = Color.FromArgb(59, 130, 246);
            cmbTimeSlot.ItemHeight = 36;
            cmbTimeSlot.Location = new Point(552, 74);
            cmbTimeSlot.Name = "cmbTimeSlot";
            cmbTimeSlot.Size = new Size(160, 42);
            cmbTimeSlot.TabIndex = 13;
            lblTimeSlot.BackColor = Color.Transparent;
            lblTimeSlot.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            lblTimeSlot.ForeColor = Color.FromArgb(51, 65, 85);
            lblTimeSlot.Location = new Point(552, 49);
            lblTimeSlot.Name = "lblTimeSlot";
            lblTimeSlot.Size = new Size(59, 19);
            lblTimeSlot.TabIndex = 12;
            lblTimeSlot.Text = "Time";
            cmbClassroom.BackColor = Color.Transparent;
            cmbClassroom.BorderColor = Color.FromArgb(203, 213, 225);
            cmbClassroom.BorderRadius = 8;
            cmbClassroom.DrawMode = DrawMode.OwnerDrawFixed;
            cmbClassroom.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbClassroom.FocusedColor = Color.FromArgb(37, 99, 235);
            cmbClassroom.FocusedState.BorderColor = Color.FromArgb(37, 99, 235);
            cmbClassroom.Font = new Font("Segoe UI", 10F);
            cmbClassroom.ForeColor = Color.FromArgb(15, 23, 42);
            cmbClassroom.HoverState.BorderColor = Color.FromArgb(59, 130, 246);
            cmbClassroom.ItemHeight = 36;
            cmbClassroom.Location = new Point(376, 74);
            cmbClassroom.Name = "cmbClassroom";
            cmbClassroom.Size = new Size(160, 42);
            cmbClassroom.TabIndex = 11;
            lblClassroom.BackColor = Color.Transparent;
            lblClassroom.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            lblClassroom.ForeColor = Color.FromArgb(51, 65, 85);
            lblClassroom.Location = new Point(376, 49);
            lblClassroom.Name = "lblClassroom";
            lblClassroom.Size = new Size(66, 19);
            lblClassroom.TabIndex = 10;
            lblClassroom.Text = "Room";
            cmbFacultyMember.BackColor = Color.Transparent;
            cmbFacultyMember.BorderColor = Color.FromArgb(203, 213, 225);
            cmbFacultyMember.BorderRadius = 8;
            cmbFacultyMember.DrawMode = DrawMode.OwnerDrawFixed;
            cmbFacultyMember.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbFacultyMember.FocusedColor = Color.FromArgb(37, 99, 235);
            cmbFacultyMember.FocusedState.BorderColor = Color.FromArgb(37, 99, 235);
            cmbFacultyMember.Font = new Font("Segoe UI", 10F);
            cmbFacultyMember.ForeColor = Color.FromArgb(15, 23, 42);
            cmbFacultyMember.HoverState.BorderColor = Color.FromArgb(59, 130, 246);
            cmbFacultyMember.ItemHeight = 36;
            cmbFacultyMember.Location = new Point(200, 74);
            cmbFacultyMember.Name = "cmbFacultyMember";
            cmbFacultyMember.Size = new Size(160, 42);
            cmbFacultyMember.TabIndex = 9;
            lblFacultyMember.BackColor = Color.Transparent;
            lblFacultyMember.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            lblFacultyMember.ForeColor = Color.FromArgb(51, 65, 85);
            lblFacultyMember.Location = new Point(200, 49);
            lblFacultyMember.Name = "lblFacultyMember";
            lblFacultyMember.Size = new Size(101, 19);
            lblFacultyMember.TabIndex = 8;
            lblFacultyMember.Text = "Teacher";
            cmbSubject.BackColor = Color.Transparent;
            cmbSubject.BorderColor = Color.FromArgb(203, 213, 225);
            cmbSubject.BorderRadius = 8;
            cmbSubject.DrawMode = DrawMode.OwnerDrawFixed;
            cmbSubject.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbSubject.FocusedColor = Color.FromArgb(37, 99, 235);
            cmbSubject.FocusedState.BorderColor = Color.FromArgb(37, 99, 235);
            cmbSubject.Font = new Font("Segoe UI", 10F);
            cmbSubject.ForeColor = Color.FromArgb(15, 23, 42);
            cmbSubject.HoverState.BorderColor = Color.FromArgb(59, 130, 246);
            cmbSubject.ItemHeight = 36;
            cmbSubject.Location = new Point(24, 74);
            cmbSubject.Name = "cmbSubject";
            cmbSubject.Size = new Size(160, 42);
            cmbSubject.TabIndex = 7;
            lblSubject.BackColor = Color.Transparent;
            lblSubject.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            lblSubject.ForeColor = Color.FromArgb(51, 65, 85);
            lblSubject.Location = new Point(24, 49);
            lblSubject.Name = "lblSubject";
            lblSubject.Size = new Size(47, 19);
            lblSubject.TabIndex = 6;
            lblSubject.Text = "Subject";
            cmbDayOfWeek.BackColor = Color.Transparent;
            cmbDayOfWeek.BorderColor = Color.FromArgb(203, 213, 225);
            cmbDayOfWeek.BorderRadius = 8;
            cmbDayOfWeek.DrawMode = DrawMode.OwnerDrawFixed;
            cmbDayOfWeek.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbDayOfWeek.FocusedColor = Color.FromArgb(37, 99, 235);
            cmbDayOfWeek.FocusedState.BorderColor = Color.FromArgb(37, 99, 235);
            cmbDayOfWeek.Font = new Font("Segoe UI", 10F);
            cmbDayOfWeek.ForeColor = Color.FromArgb(15, 23, 42);
            cmbDayOfWeek.HoverState.BorderColor = Color.FromArgb(59, 130, 246);
            cmbDayOfWeek.ItemHeight = 36;
            cmbDayOfWeek.Items.AddRange(new object[] { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday" });
            cmbDayOfWeek.Location = new Point(728, 74);
            cmbDayOfWeek.Name = "cmbDayOfWeek";
            cmbDayOfWeek.Size = new Size(160, 42);
            cmbDayOfWeek.TabIndex = 5;
            lblDayOfWeek.BackColor = Color.Transparent;
            lblDayOfWeek.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            lblDayOfWeek.ForeColor = Color.FromArgb(51, 65, 85);
            lblDayOfWeek.Location = new Point(728, 49);
            lblDayOfWeek.Name = "lblDayOfWeek";
            lblDayOfWeek.Size = new Size(82, 19);
            lblDayOfWeek.TabIndex = 4;
            lblDayOfWeek.Text = "Day";
            txtScheduleId.BorderColor = Color.FromArgb(226, 232, 240);
            txtScheduleId.BorderRadius = 8;
            txtScheduleId.Cursor = Cursors.IBeam;
            txtScheduleId.DefaultText = "";
            txtScheduleId.DisabledState.BorderColor = Color.FromArgb(226, 232, 240);
            txtScheduleId.DisabledState.FillColor = Color.FromArgb(248, 250, 252);
            txtScheduleId.DisabledState.ForeColor = Color.FromArgb(100, 116, 139);
            txtScheduleId.Enabled = false;
            txtScheduleId.FillColor = Color.FromArgb(248, 250, 252);
            txtScheduleId.Font = new Font("Segoe UI", 10F);
            txtScheduleId.ForeColor = Color.FromArgb(100, 116, 139);
            txtScheduleId.Location = new Point(24, 84);
            txtScheduleId.Margin = new Padding(3, 4, 3, 4);
            txtScheduleId.Name = "txtScheduleId";
            txtScheduleId.PlaceholderForeColor = Color.FromArgb(148, 163, 184);
            txtScheduleId.PlaceholderText = "Auto";
            txtScheduleId.SelectedText = "";
            txtScheduleId.Size = new Size(132, 42);
            txtScheduleId.TabIndex = 3;
            txtScheduleId.Visible = false;
            lblScheduleId.BackColor = Color.Transparent;
            lblScheduleId.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            lblScheduleId.ForeColor = Color.FromArgb(51, 65, 85);
            lblScheduleId.Location = new Point(24, 59);
            lblScheduleId.Name = "lblScheduleId";
            lblScheduleId.Size = new Size(74, 19);
            lblScheduleId.TabIndex = 2;
            lblScheduleId.Text = "Schedule ID";
            lblScheduleId.Visible = false;
            lblEditorSubtitle.BackColor = Color.Transparent;
            lblEditorSubtitle.Font = new Font("Segoe UI", 9F);
            lblEditorSubtitle.ForeColor = Color.FromArgb(100, 116, 139);
            lblEditorSubtitle.Location = new Point(24, 34);
            lblEditorSubtitle.Name = "lblEditorSubtitle";
            lblEditorSubtitle.Size = new Size(312, 17);
            lblEditorSubtitle.TabIndex = 1;
            lblEditorSubtitle.Text = "Prepare schedule session details before applying an action.";
            lblEditorTitle.BackColor = Color.Transparent;
            lblEditorTitle.Font = new Font("Segoe UI Semibold", 13F, FontStyle.Bold);
            lblEditorTitle.ForeColor = Color.FromArgb(15, 23, 42);
            lblEditorTitle.Location = new Point(24, 9);
            lblEditorTitle.Name = "lblEditorTitle";
            lblEditorTitle.Size = new Size(128, 25);
            lblEditorTitle.TabIndex = 0;
            lblEditorTitle.Text = "Manual Schedule Entry";
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(245, 247, 250);
            ClientSize = new Size(1500, 820);
            Controls.Add(pnlMain);
            Controls.Add(pnlSidebar);
            Font = new Font("Segoe UI", 9F);
            MinimumSize = new Size(1180, 720);
            Name = "SchedulesForm";
            Text = "Schedules Management";
            pnlSidebar.ResumeLayout(false);
            pnlSidebar.PerformLayout();
            pnlMain.ResumeLayout(false);
            pnlWorkspace.ResumeLayout(false);
            pnlSchedulesTable.ResumeLayout(false);
            pnlSchedulesTable.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvSchedules).EndInit();
            pnlScheduleFilters.ResumeLayout(false);
            pnlScheduleFilters.PerformLayout();
            pnlScheduleEditor.ResumeLayout(false);
            pnlScheduleEditor.PerformLayout();
            ResumeLayout(false);
        }
        private Guna.UI2.WinForms.Guna2Panel pnlSidebar = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblApplicationName = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblSidebarSubtitle = null!;
        private Guna.UI2.WinForms.Guna2Separator separatorSidebar = null!;
        private Guna.UI2.WinForms.Guna2Button btnNavigationBranches = null!;
        private Guna.UI2.WinForms.Guna2Button btnNavigationStudyYears = null!;
        private Guna.UI2.WinForms.Guna2Button btnNavigationSubjects = null!;
        private Guna.UI2.WinForms.Guna2Button btnNavigationClassrooms = null!;
        private Guna.UI2.WinForms.Guna2Button btnNavigationTimeSlots = null!;
        private Guna.UI2.WinForms.Guna2Button btnNavigationFaculty = null!;
        private Guna.UI2.WinForms.Guna2Button btnNavigationSchedules = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblSidebarFooter = null!;
        private Guna.UI2.WinForms.Guna2Panel pnlMain = null!;
        private Guna.UI2.WinForms.Guna2Panel pnlWorkspace = null!;
        private Guna.UI2.WinForms.Guna2Panel pnlScheduleFilters = null!;
        private Guna.UI2.WinForms.Guna2ComboBox cmbFacultyFilter = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblFacultyFilter = null!;
        private Guna.UI2.WinForms.Guna2ComboBox cmbSectionFilter = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblSectionFilter = null!;
        private Guna.UI2.WinForms.Guna2ComboBox cmbStudyYearFilter = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblStudyYearFilter = null!;
        private Guna.UI2.WinForms.Guna2Panel pnlScheduleEditor = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblEditorTitle = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblEditorSubtitle = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblScheduleId = null!;
        private Guna.UI2.WinForms.Guna2TextBox txtScheduleId = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblDayOfWeek = null!;
        private Guna.UI2.WinForms.Guna2ComboBox cmbDayOfWeek = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblSubject = null!;
        private Guna.UI2.WinForms.Guna2ComboBox cmbSubject = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblFacultyMember = null!;
        private Guna.UI2.WinForms.Guna2ComboBox cmbFacultyMember = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblClassroom = null!;
        private Guna.UI2.WinForms.Guna2ComboBox cmbClassroom = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblTimeSlot = null!;
        private Guna.UI2.WinForms.Guna2ComboBox cmbTimeSlot = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblStudyYear = null!;
        private Guna.UI2.WinForms.Guna2ComboBox cmbStudyYear = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblBranch = null!;
        private Guna.UI2.WinForms.Guna2ComboBox cmbBranch = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblSection = null!;
        private Guna.UI2.WinForms.Guna2ComboBox cmbSection = null!;
        private Guna.UI2.WinForms.Guna2Button btnGenerateSchedule = null!;
        private Guna.UI2.WinForms.Guna2Button btnAddSchedule = null!;
        private Guna.UI2.WinForms.Guna2Button btnUpdateSchedule = null!;
        private Guna.UI2.WinForms.Guna2Button btnDeleteSchedule = null!;
        private Guna.UI2.WinForms.Guna2Button btnClearScheduleForm = null!;
        private Guna.UI2.WinForms.Guna2Button btnExportSchedulePdf = null!;
        private Guna.UI2.WinForms.Guna2Panel pnlSchedulesTable = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblTableTitle = null!;
        private Guna.UI2.WinForms.Guna2HtmlLabel lblTableSubtitle = null!;
        private Guna.UI2.WinForms.Guna2DataGridView dgvSchedules = null!;
        private System.Windows.Forms.DataGridViewTextBoxColumn colScheduleId = null!;
        private System.Windows.Forms.DataGridViewTextBoxColumn colDayOfWeek = null!;
        private System.Windows.Forms.DataGridViewTextBoxColumn colSubject = null!;
        private System.Windows.Forms.DataGridViewTextBoxColumn colFacultyMember = null!;
        private System.Windows.Forms.DataGridViewTextBoxColumn colClassroom = null!;
        private System.Windows.Forms.DataGridViewTextBoxColumn colTimeSlot = null!;
        private System.Windows.Forms.DataGridViewTextBoxColumn colStudyYear = null!;
        private System.Windows.Forms.DataGridViewTextBoxColumn colBranch = null!;
        private System.Windows.Forms.DataGridViewTextBoxColumn colSection = null!;

    }
}

